(() => {
  const REPO = window.PORTFOLIO_REPO || "voidflare-root/profile";
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => Array.from(r.querySelectorAll(s));
  const title = (n) => n.replace(/\.[^.]+$/, "").replace(/[-_]+/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());
  const unique = (arr, key) => { const seen = new Set(); return arr.filter((x) => { const k = key(x); if (seen.has(k)) return false; seen.add(k); return true; }); };
  const skills = [
    ["fa-brands fa-android", "Android Development"], ["fa-solid fa-code", "Kotlin"], ["fa-brands fa-python", "Python"],
    ["fa-solid fa-globe", "Web Development"], ["fa-brands fa-java", "Java"], ["fa-brands fa-html5", "HTML"],
    ["fa-brands fa-css3-alt", "CSS"], ["fa-solid fa-laptop-code", "Coding"], ["fa-solid fa-user-secret", "Hacking"],
    ["fa-solid fa-robot", "AI Tools"], ["fa-brands fa-telegram", "Telegram Bots"]
  ];

  function styles() {
    document.querySelector("#premiumUiStyles")?.remove();
    const st = document.createElement("style");
    st.id = "premiumUiStyles";
    st.textContent = `
      body{background:radial-gradient(circle at 16% -8%,rgba(168,85,247,.34),transparent 36%),radial-gradient(circle at 92% 12%,rgba(34,197,94,.12),transparent 28%),radial-gradient(circle at 50% 112%,rgba(138,43,226,.22),transparent 34%),#030306!important}
      .profile-card,.posts-section{border-color:rgba(190,132,255,.38)!important;background:linear-gradient(145deg,rgba(255,255,255,.105),rgba(255,255,255,.035))!important;box-shadow:0 24px 90px rgba(0,0,0,.48),0 0 42px rgba(168,85,247,.16),inset 0 1px 0 rgba(255,255,255,.12)!important}.dp-ring{background:conic-gradient(from 180deg,#8a2be2,#d8b4fe,#fff,#a855f7,#8a2be2)!important;box-shadow:0 0 26px rgba(168,85,247,.72),0 0 70px rgba(168,85,247,.28)!important}.name-row{display:flex!important;align-items:center!important;gap:12px!important;flex-wrap:nowrap!important;min-width:0!important}.name-row h1{flex:0 1 auto!important;min-width:0!important}.instagram-link{flex:0 0 auto!important}h1{background:linear-gradient(180deg,#fff,#e8d5ff 45%,#a855f7);-webkit-background-clip:text;background-clip:text;color:transparent!important;text-shadow:0 0 28px rgba(168,85,247,.34)!important}
      .info-section,.stories-section,#noteModal,.note-modal,.note-modal.is-open{display:none!important;visibility:hidden!important;pointer-events:none!important;width:0!important;height:0!important;max-height:0!important;overflow:hidden!important}.tab-panel[hidden]{display:none!important}.notes-list:empty{display:none!important}
      .section-title{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;align-items:center;gap:8px}.posts-toggle,.others-toggle,.notes-toggle,.tools-toggle,.projects-toggle{min-height:40px;border:1px solid rgba(168,85,247,.32)!important;border-radius:999px;display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:0 10px;color:#fff;background:linear-gradient(145deg,rgba(255,255,255,.12),rgba(255,255,255,.045))!important;cursor:pointer;font-size:.8rem;font-weight:900;box-shadow:inset 0 1px 0 rgba(255,255,255,.1),0 10px 28px rgba(0,0,0,.18)!important}.posts-toggle.is-open,.others-toggle.is-open,.notes-toggle.is-open,.tools-toggle.is-open,.projects-toggle.is-open{border-color:rgba(216,180,254,.64)!important;background:linear-gradient(145deg,rgba(168,85,247,.28),rgba(255,255,255,.07))!important;box-shadow:0 0 32px rgba(168,85,247,.42),inset 0 1px 0 rgba(255,255,255,.14)!important}
      .post-card{border:1px solid rgba(216,180,254,.2)!important;border-radius:20px!important;background:#080810!important;box-shadow:0 14px 40px rgba(0,0,0,.32),0 0 24px rgba(168,85,247,.1),inset 0 1px 0 rgba(255,255,255,.08)!important}.tab-card-grid,.notes-panel,.projects-panel{padding:12px!important}.notes-list{display:grid;gap:10px}.tab-card-grid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:10px!important}.tab-card-grid article{min-height:116px!important;border:1px solid rgba(216,180,254,.34)!important;border-radius:22px!important;display:grid!important;place-items:center!important;align-content:center!important;gap:10px!important;padding:14px 8px!important;text-align:center!important;background:radial-gradient(circle at 50% 0,rgba(216,180,254,.18),transparent 46%),linear-gradient(145deg,rgba(168,85,247,.18),rgba(255,255,255,.045))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.1),0 10px 28px rgba(0,0,0,.18)!important}.tab-card-grid article i{width:42px;height:42px;border:1px solid rgba(216,180,254,.38);border-radius:16px;display:grid;place-items:center;color:#fff!important;background:rgba(168,85,247,.2);font-size:1.35rem!important;box-shadow:0 0 26px rgba(168,85,247,.34)}.tab-card-grid article strong{font-size:.78rem!important;line-height:1.2!important;overflow-wrap:anywhere}
      .note-item,.project-item{min-height:82px;border:1px solid rgba(168,85,247,.28)!important;border-radius:20px;display:grid;gap:10px;padding:13px;background:linear-gradient(135deg,rgba(138,43,226,.14),rgba(168,85,247,.055)),rgba(255,255,255,.055)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 12px 34px rgba(0,0,0,.22)!important}.note-actions,.project-actions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.project-actions.no-open{grid-template-columns:repeat(2,minmax(0,1fr))}.note-actions a,.note-actions button,.project-actions a,.project-actions button{min-height:38px;border:1px solid rgba(168,85,247,.3);border-radius:14px;display:inline-flex;align-items:center;justify-content:center;gap:7px;color:#fff;background:rgba(255,255,255,.06);cursor:pointer;font-size:.8rem;font-weight:900;text-decoration:none}.project-title{display:flex;align-items:center;gap:9px;color:#fff;font-weight:950}.project-title i{width:34px;height:34px;border:1px solid rgba(216,180,254,.35);border-radius:13px;display:grid;place-items:center;color:#d8b4fe;background:rgba(168,85,247,.16);box-shadow:0 0 20px rgba(168,85,247,.24)}.project-desc{margin:0;color:#b8b8b8;font-size:.82rem;line-height:1.55}.empty-state{margin:0;color:#b8b8b8;line-height:1.6}
      @media(max-width:1023px){.app-shell{width:min(100%,980px)!important;display:block!important;margin:0 auto!important}.profile-card,.posts-section{width:min(720px,100%)!important;margin-left:auto!important;margin-right:auto!important}.posts-section{margin-top:16px!important}}@media(min-width:1024px){.app-shell{width:min(1120px,calc(100% - 48px))!important;display:grid!important;grid-template-columns:minmax(360px,430px) minmax(0,1fr)!important;gap:22px!important;align-items:start!important}.profile-card{position:sticky!important;top:22px!important;width:100%!important;margin:0!important;grid-column:1!important;grid-row:1 / span 8!important}.posts-section{width:100%!important;grid-column:2!important;margin-top:0!important}}@media(max-width:520px){.app-shell{padding:12px 10px 42px!important}.profile-card{padding:16px!important;border-radius:26px!important}.section-title{gap:5px!important;padding:13px!important}.posts-toggle,.others-toggle,.notes-toggle,.tools-toggle,.projects-toggle{min-height:38px!important;padding:0 4px!important;font-size:.68rem!important;gap:4px}.post-grid,.tab-card-grid{gap:7px!important;padding:8px!important}.note-actions,.project-actions,.project-actions.no-open{grid-template-columns:1fr!important}}
    `;
    document.head.appendChild(st);
  }

  function ensurePanel(name, icon, label, listId) {
    let panel = $(`.tab-panel[data-panel="${name}"]`);
    if (!panel) { panel = document.createElement("div"); panel.dataset.panel = name; panel.hidden = true; $(".posts-section")?.appendChild(panel); }
    panel.className = `tab-panel notes-panel ${name === "projects" ? "projects-panel" : ""}`;
    if (!$(`#${listId}`, panel)) panel.innerHTML = `<div class="notes-head"><i class="fa-solid ${icon}"></i><strong>${label}</strong></div><div class="notes-list" id="${listId}"></div>`;
  }
  function setup() {
    const bar = $("#posts .section-title");
    if (bar && !$("#projectsToggle")) { const b = document.createElement("button"); b.id = "projectsToggle"; b.className = "projects-toggle"; b.type = "button"; b.innerHTML = '<i class="fa-solid fa-folder-open"></i><span>Projects</span>'; bar.appendChild(b); }
    ensurePanel("notes", "fa-note-sticky", "Notes", "notesList"); ensurePanel("tools", "fa-screwdriver-wrench", "Tools", "toolsList"); ensurePanel("projects", "fa-folder-open", "Projects", "projectsList");
    const sk = $('.tab-panel[data-panel="skills"]'); if (sk) { sk.className = "tab-panel tab-card-grid"; sk.innerHTML = skills.map(([i,l]) => `<article><i class="${i}"></i><strong>${l}</strong></article>`).join(""); }
  }
  function activate(name) {
    $$(".tab-panel").forEach(p => { const a = p.dataset.panel === name; p.hidden = !a; p.style.display = a ? "" : "none"; p.classList.toggle("is-active", a); });
    Object.entries({posts:"#postsToggle", skills:"#othersToggle", notes:"#notesToggle", tools:"#toolsToggle", projects:"#projectsToggle"}).forEach(([k,s]) => $(s)?.classList.toggle("is-open", k === name));
    document.body.classList.toggle("is-others-mode", name !== "posts");
    if (name === "notes") loadFolder("notes", "#notesList"); if (name === "tools") loadFolder("tools", "#toolsList"); if (name === "projects") loadProjects();
  }
  async function files(folder) {
    try { const r = await fetch(`https://api.github.com/repos/${REPO}/contents/${folder}?t=${Date.now()}`, { cache:"no-store" }); if (r.ok) return (await r.json()).filter(f => f.type === "file" && !f.name.startsWith(".") && !f.name.toLowerCase().startsWith("readme.") && f.download_url); } catch {}
    return [];
  }
  function norm(u) { if (!u) return ""; try { const p = new URL(u.trim(), location.href); if (p.hostname === "github.com" && p.pathname.includes("/blob/")) { const a = p.pathname.split("/").filter(Boolean), i = a.indexOf("blob") + 1; return `https://raw.githubusercontent.com/${a[0]}/${a[1]}/${a[i]}/${a.slice(i+1).map(encodeURIComponent).join("/")}`; } return p.toString(); } catch { return u.trim(); } }
  function parseProject(text, file) {
    const base = title(file.name); return text.split(/\r?\n/).map(x => x.trim()).filter(Boolean).map(line => { const m = line.match(/^(app|apk|src|source|sourcecode|code|zip)\s*[:=-]?\s+(https?:\/\/\S+)$/i); if (m) { const type = m[1].toLowerCase().replace(/[^a-z]/g, ""), label = type === "app" || type === "apk" ? "App" : ["src","source","sourcecode","code"].includes(type) ? "Source Code" : type === "zip" ? "Zip" : "Project"; return { name:`${base} ${label}`, description:`${label} direct download.`, download:norm(m[2]), type }; } const d = line.match(/^(https?:\/\/\S+)$/i); return d ? { name:base, description:"Project direct download.", download:norm(d[1]), type:"" } : null; }).filter(Boolean);
  }
  async function projectFromFile(file) { if (/\.(txt|md)$/i.test(file.name)) { try { const r = await fetch(file.download_url, { cache:"no-store" }); if (r.ok) return parseProject(await r.text(), file); } catch {} } return [{ name:title(file.name), description:"Project file ready for download.", download:norm(file.download_url), type:"" }]; }
  function canOpen(p) { const t = String(p.type || "").toLowerCase().replace(/[^a-z]/g, ""); if (["src","source","sourcecode","code","zip"].includes(t)) return true; try { return new URL(p.download, location.href).pathname.toLowerCase().endsWith(".zip"); } catch { return /\.zip(?:$|[?#])/i.test(p.download || ""); } }
  function filename(url, fallback) { try { const f = decodeURIComponent(new URL(url, location.href).pathname.split("/").filter(Boolean).pop() || ""); if (f && f.includes(".")) return f; } catch {} return fallback.replace(/[^\w.-]+/g, "-") || "download"; }
  function download(url, name) { const a = document.createElement("a"); a.href = url; a.download = name; a.rel = "noreferrer"; document.body.appendChild(a); a.click(); a.remove(); }
  async function share(label, url) { if (navigator.share) { try { await navigator.share({ title:label, url }); return; } catch { return; } } await navigator.clipboard.writeText(url); const t = $("#toast"); if (t) { t.textContent = "Website link copied."; t.classList.add("show"); setTimeout(() => t.classList.remove("show"), 1800); } }
  function projectCard(p) { const o = canOpen(p), e = document.createElement("article"); e.className = "project-item"; e.innerHTML = `<div class="project-title"><i class="fa-solid fa-folder-open"></i><strong>${p.name}</strong></div><p class="project-desc">${p.description}</p><div class="project-actions ${o ? "" : "no-open"}">${o ? '<a class="project-open" href="#projects"><i class="fa-solid fa-eye"></i><span>Open</span></a>' : ""}<button class="project-download" type="button"><i class="fa-solid fa-download"></i><span>Download</span></button><button class="project-share" type="button"><i class="fa-solid fa-share-nodes"></i><span>Share</span></button></div>`; $(".project-download", e).dataset.download = p.download || ""; $(".project-open", e)?.addEventListener("click", ev => { ev.preventDefault(); download(p.download, filename(p.download, p.name)); }); $(".project-download", e).onclick = () => download(p.download, filename(p.download, p.name)); $(".project-share", e).onclick = () => share(p.name, `${location.origin}${location.pathname}?project=${encodeURIComponent(p.name)}#projects`); return e; }
  async function loadProjects() { const list = $("#projectsList"); if (!list) return; list.innerHTML = ""; const items = unique((await Promise.all((await files("projects")).map(projectFromFile))).flat(), p => `${p.name}|${p.download}`); if (!items.length) { list.innerHTML = '<p class="empty-state">Projects folder me file add karo.</p>'; return; } items.forEach(p => list.appendChild(projectCard(p))); }
  function fileCard(file, folder) { const label = title(file.name), e = document.createElement("article"); e.className = "note-item"; e.innerHTML = `<strong>${label}</strong><div class="note-actions"><a href="${file.download_url}" target="_blank" rel="noreferrer"><i class="fa-solid fa-eye"></i><span>Open</span></a><a href="${file.download_url}" download="${file.name}"><i class="fa-solid fa-download"></i><span>Download</span></a><button class="file-share" type="button"><i class="fa-solid fa-share-nodes"></i><span>Share</span></button></div>`; $(".file-share", e).onclick = () => share(label, `${location.origin}${location.pathname}?${folder}=${encodeURIComponent(file.name)}#${folder}`); return e; }
  async function loadFolder(folder, selector) { const list = $(selector); if (!list) return; list.innerHTML = ""; const items = unique(await files(folder), f => `${f.name}|${f.download_url}`); if (!items.length) { list.innerHTML = `<p class="empty-state">${folder} folder me file add karo.</p>`; return; } items.forEach(f => list.appendChild(fileCard(f, folder))); }
  function bind() { if (document.body.dataset.allTabsFixed === "1") return; document.body.dataset.allTabsFixed = "1"; document.addEventListener("click", e => { const b = e.target.closest("#postsToggle,#othersToggle,#notesToggle,#toolsToggle,#projectsToggle"); if (!b) return; e.preventDefault(); e.stopImmediatePropagation(); activate(b.id === "postsToggle" ? "posts" : b.id === "othersToggle" ? "skills" : b.id === "notesToggle" ? "notes" : b.id === "toolsToggle" ? "tools" : "projects"); }, true); }
  function init() { styles(); setup(); bind(); loadFolder("notes", "#notesList"); loadFolder("tools", "#toolsList"); loadProjects(); activate(new URLSearchParams(location.search).has("project") || location.hash === "#projects" ? "projects" : ($(".tab-panel.is-active")?.dataset.panel || "posts")); }
  if (document.readyState === "loading") window.addEventListener("DOMContentLoaded", init); else init(); window.addEventListener("load", () => setTimeout(init, 250));
})();
